# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08kv.proto\"\x1a\n\x02Kv\x12\t\n\x01k\x18\x01 \x01(\x03\x12\t\n\x01v\x18\x02 \x01(\x05\"\x15\n\x03Kvs\x12\x0e\n\x01s\x18\x01 \x03(\x0b\x32\x03.Kvb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KV._serialized_start=12
  _KV._serialized_end=38
  _KVS._serialized_start=40
  _KVS._serialized_end=61
# @@protoc_insertion_point(module_scope)
